#latest might not be a good idea, if rest of program becomes incompatible with the latest version
#latest prohibited in subject
FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
ENV

